---
kind: pipeline
name: ci

steps:
  - name: install
    image: iknpx/archnode
    commands:
      - yarn --silent
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request

  - name: lint
    image: iknpx/archnode
    commands:
      - yarn lint
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request

  - name: dist
    image: iknpx/archnode
    commands:
      - yarn dist
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  - name: make/image
    image: plugins/docker
    settings:
      repo: iknpx/express-rest-api
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      branch:
        - master
      event:
        - push
